/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.DangNhapBUS;
import BUS.GiamGiaBUS;
import DTO.GiamGiaDTO;
import DTO.NhanVienDTO;
import Utils.Sercurity;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.security.tools.KeyStoreUtil;

/**
 *
 * @author HeoBayMau
 */
public class GiamGiaGUI extends javax.swing.JFrame {
    private DefaultTableModel ds;
    private GiamGiaBUS ggb = new GiamGiaBUS();
    private int cr;
    /**
     * Creates new form GiamGiaGUI
     */
    public GiamGiaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelMaGiamGia = new javax.swing.JLabel();
        LabelMucGiam = new javax.swing.JLabel();
        LabelGhiChu = new javax.swing.JLabel();
        LabelHanDung = new javax.swing.JLabel();
        LabelTaiKhoan = new javax.swing.JLabel();
        LabelMatKhau = new javax.swing.JLabel();
        LabelPhieuGiamGia = new javax.swing.JLabel();
        LabelThongTinQuanLy = new javax.swing.JLabel();
        txtMaGiamGia = new javax.swing.JTextField();
        txtMucGiam = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtHanDung = new javax.swing.JTextField();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableGiamGia = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GIẢM GIÁ");

        LabelMaGiamGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMaGiamGia.setText("Mã giảm giá");

        LabelMucGiam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMucGiam.setText("Mức giảm");

        LabelGhiChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGhiChu.setText("Ghi chú");
        LabelGhiChu.setToolTipText("");

        LabelHanDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelHanDung.setText("Hạn dùng");

        LabelTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTaiKhoan.setText("Tài khoản");

        LabelMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMatKhau.setText("Mật khẩu");

        LabelPhieuGiamGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPhieuGiamGia.setText("Phiếu giảm giá");

        LabelThongTinQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelThongTinQuanLy.setText("Thông tin quản lý");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelHanDung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHanDung, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelThongTinQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelPhieuGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LabelPhieuGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHanDung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHanDung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelThongTinQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        TableGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableGiamGia);

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnHienThi.setText("Hiển thị");
        btnHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienThiMouseClicked(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienThiMouseClicked
        Vector header = new Vector();
        header.add("Mã giảm giá");
        header.add("Mức giảm");
        header.add("Ghi chú");
        header.add("Hạn dùng");
        DefaultTableModel table = new DefaultTableModel(header,0);
        ArrayList<GiamGiaDTO> ar = null;
        try {
            ar = ggb.getGiamGia();
            GiamGiaDTO ggd = new GiamGiaDTO();
            for(int i=0; i<ar.size(); i++)
            {
                Vector row = new Vector();
                ggd = ar.get(i);
                row.add(ggd.getMaGiamGia());
                row.add(ggd.getMucGiam());
                row.add(ggd.getGhiChu());
                row.add(ggd.getHanDung());
                table.addRow(row);
            }
            ds = table;
            TableGiamGia.setModel(table);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnHienThiMouseClicked

    private void TableGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableGiamGiaMouseClicked
        int n = TableGiamGia.getSelectedRow();
        cr = n;
        txtMaGiamGia.setText(TableGiamGia.getValueAt(n, 0).toString());
        txtMucGiam.setText(TableGiamGia.getValueAt(n, 1).toString());
        txtGhiChu.setText(TableGiamGia.getValueAt(n, 2).toString());
        txtHanDung.setText(TableGiamGia.getValueAt(n, 3).toString());
    }//GEN-LAST:event_TableGiamGiaMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        try {
            GiamGiaDTO ggd = new GiamGiaDTO();
            ggd.setMaGiamGia(txtMaGiamGia.getText());
            ggd.setMucGiam(Integer.parseInt(txtMucGiam.getText()));
            ggd.setGhiChu(txtGhiChu.getText());
            ggd.setHanDung(txtHanDung.getText());
            ArrayList<NhanVienDTO> ar = null;
            if(txtTaiKhoan.getText().equals(null) || txtTaiKhoan.getText()=="")
            {
                JOptionPane.showMessageDialog(null,"Không thể để username trống");
                return;
            }
            DangNhapBUS dnb = new DangNhapBUS();
            try {
                ar = dnb.getDangNhap("taikhoan="+"'"+txtTaiKhoan.getText()+"'");
                for(int i=0; i<ar.size(); i++)
                {
                    NhanVienDTO nvd = new NhanVienDTO();
                    nvd = ar.get(i);
                    String md5MatKhau = Sercurity.MD5(txtMatKhau.getText());
                    if(nvd.getMatKhau().equals(md5MatKhau))
                    {
                        if(nvd.getRole().equals("admin"))
                        {
                            ggb.Insert(ggd);
                            Vector row = new Vector();
                            row.add(txtMaGiamGia.getText());
                            row.add(txtMucGiam.getText());
                            row.add(txtGhiChu.getText());
                            row.add(txtHanDung.getText());
                            ds.addRow(row);
                            TableGiamGia.setModel(ds);
                        }
                    }
                }
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        try {
            ArrayList<NhanVienDTO> ar = null;
            if(txtTaiKhoan.getText().equals(null) || txtTaiKhoan.getText()=="")
            {
                JOptionPane.showMessageDialog(null,"Không thể để username trống");
                return;
            }
            DangNhapBUS dnb = new DangNhapBUS();
            try {
                ar = dnb.getDangNhap("taikhoan="+"'"+txtTaiKhoan.getText()+"'");
                for(int i=0; i<ar.size(); i++)
                {
                    NhanVienDTO nvd = new NhanVienDTO();
                    nvd = ar.get(i);
                    String md5MatKhau = Sercurity.MD5(txtMatKhau.getText());
                    if(nvd.getMatKhau().equals(md5MatKhau))
                    {
                        if(nvd.getRole().equals("admin"))
                        {
                            GiamGiaDTO ggd = new GiamGiaDTO();
                            ggd.setMaGiamGia(txtMaGiamGia.getText());
                            ggd.setMucGiam(Integer.parseInt(txtMucGiam.getText()));
                            ggd.setGhiChu(txtGhiChu.getText());
                            ggd.setHanDung(txtHanDung.getText());
                            ggb.Update(ggd);
                            ds.setValueAt(txtMaGiamGia.getText(), cr, 0);
                            ds.setValueAt(txtMucGiam.getText(), cr, 1);
                            ds.setValueAt(txtGhiChu.getText(), cr, 2);
                            ds.setValueAt(txtHanDung.getText(), cr, 3);
                            TableGiamGia.setModel(ds);
                        }
                    }
                }
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        try {
            ArrayList<NhanVienDTO> ar = null;
            if(txtTaiKhoan.getText().equals(null) || txtTaiKhoan.getText()=="")
            {
                JOptionPane.showMessageDialog(null,"Không thể để username trống");
                return;
            }
            DangNhapBUS dnb = new DangNhapBUS();
            try {
                ar = dnb.getDangNhap("taikhoan="+"'"+txtTaiKhoan.getText()+"'");
                for(int i=0; i<ar.size(); i++)
                {
                    NhanVienDTO nvd = new NhanVienDTO();
                    nvd = ar.get(i);
                    String md5MatKhau = Sercurity.MD5(txtMatKhau.getText());
                    if(nvd.getMatKhau().equals(md5MatKhau))
                    {
                        if(nvd.getRole().equals("admin"))
                        {
                            GiamGiaDTO ggd = new GiamGiaDTO();
                            ggd.setMaGiamGia(txtMaGiamGia.getText());
                            ggd.setMucGiam(Integer.parseInt(txtMucGiam.getText()));
                            ggd.setGhiChu(txtGhiChu.getText());
                            ggd.setHanDung(txtHanDung.getText());
                            ggb.Delete(ggd);
                            ds.removeRow(cr);
                            TableGiamGia.setModel(ds);
                        }
                    }
                }
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiamGiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiamGiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiamGiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiamGiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiamGiaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelGhiChu;
    private javax.swing.JLabel LabelHanDung;
    private javax.swing.JLabel LabelMaGiamGia;
    private javax.swing.JLabel LabelMatKhau;
    private javax.swing.JLabel LabelMucGiam;
    private javax.swing.JLabel LabelPhieuGiamGia;
    private javax.swing.JLabel LabelTaiKhoan;
    private javax.swing.JLabel LabelThongTinQuanLy;
    private javax.swing.JTable TableGiamGia;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHanDung;
    private javax.swing.JTextField txtMaGiamGia;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtMucGiam;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
