/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.CtNhaCungCapBUS;
import BUS.CtNhapHangBUS;
import BUS.NhaCungCapBUS;
import BUS.NhanVienBUS;
import BUS.NhapHangBUS;
import BUS.SanPhamBUS;
import DTO.CtNhaCungCapDTO;
import DTO.CtNhapHangDTO;
import DTO.NhaCungCapDTO;
import DTO.NhanVienDTO;
import DTO.NhapHangDTO;
import DTO.SanPhamDTO;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HeoBayMau
 */
public class NhapHangGUI extends javax.swing.JFrame {
    private DefaultTableModel ds;
    private DefaultTableModel ds2;
    private DefaultTableModel ds3;
    private DefaultTableModel ds4;
    private DefaultTableModel ds5;
    private NhapHangBUS nhb = new NhapHangBUS();
    private NhaCungCapBUS nccb = new NhaCungCapBUS();
    private NhanVienBUS nvb = new NhanVienBUS();
    private SanPhamBUS spb = new SanPhamBUS();
    private CtNhapHangBUS ctnhb = new CtNhapHangBUS();
    private CtNhaCungCapBUS ctnccb = new CtNhaCungCapBUS();
    private int cr;
    private int cr2;
    private int cr3;
    private int cr4;
    private int cr5;
    /**
     * Creates new form NhapHangGUI
     */
    public NhapHangGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelMaPhieuNhapHang = new javax.swing.JLabel();
        LabelMaNhaCungCap = new javax.swing.JLabel();
        LabelMaNhanVien = new javax.swing.JLabel();
        LabelNgayLap = new javax.swing.JLabel();
        LabelMaSanPham = new javax.swing.JLabel();
        LabelSoLuong = new javax.swing.JLabel();
        LabelDonGia = new javax.swing.JLabel();
        LabelPhieuNhapHang = new javax.swing.JLabel();
        LabelChiTiet = new javax.swing.JLabel();
        txtMaPhieuNhapHang = new javax.swing.JTextField();
        txtMaNhaCungCap = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        txtNgayLap = new javax.swing.JTextField();
        txtMaSanPham = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNhaCungCap = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableSanPham = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableNhapHang = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableChiTietNhapHang = new javax.swing.JTable();
        btnSuaChiTiet = new javax.swing.JButton();
        btnThemChiTiet = new javax.swing.JButton();
        btnXoaChiTiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHẬP HÀNG");

        LabelMaPhieuNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMaPhieuNhapHang.setText("Mã phiếu nhập hàng");

        LabelMaNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMaNhaCungCap.setText("Mã nhà cung cấp");

        LabelMaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMaNhanVien.setText("Mã nhân viên");
        LabelMaNhanVien.setToolTipText("");

        LabelNgayLap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNgayLap.setText("Ngày lập");

        LabelMaSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMaSanPham.setText("Mã sản phẩm");

        LabelSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSoLuong.setText("Số lượng");

        LabelDonGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDonGia.setText("Đơn giá");

        LabelPhieuNhapHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelPhieuNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPhieuNhapHang.setText("Phiếu nhập hàng");

        LabelChiTiet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelChiTiet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelChiTiet.setText("Chi tiết");

        txtMaPhieuNhapHang.setToolTipText("");

        txtMaNhaCungCap.setToolTipText("");

        txtMaNhanVien.setToolTipText("");

        txtNgayLap.setToolTipText("");

        txtMaSanPham.setToolTipText("");

        txtSoLuong.setToolTipText("");

        txtDonGia.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPhieuNhapHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelMaPhieuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaPhieuNhapHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPhieuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelMaPhieuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(LabelNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(LabelChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaPhieuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        TableNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableNhaCungCap);

        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableNhanVien);

        TableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableSanPham);

        TableNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNhapHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableNhapHang);

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnHienThi.setText("Hiển thị");
        btnHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienThiMouseClicked(evt);
            }
        });

        TableChiTietNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableChiTietNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableChiTietNhapHangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TableChiTietNhapHang);

        btnSuaChiTiet.setText("Sửa chi tiết");
        btnSuaChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaChiTietMouseClicked(evt);
            }
        });

        btnThemChiTiet.setText("Thêm chi tiết");
        btnThemChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemChiTietMouseClicked(evt);
            }
        });

        btnXoaChiTiet.setText("Xoá chi tiết");
        btnXoaChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaChiTietMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuaChiTiet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnXoaChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienThiMouseClicked
        Vector header = new Vector();
        header.add("Mã phiếu nhập hàng");
        header.add("Mã nhà cung cấp");
        header.add("Mã nhân viên");
        header.add("Ngày lập");
        header.add("Tổng tiền");
        DefaultTableModel table = new DefaultTableModel(header,0);
        ArrayList<NhapHangDTO> ar = null;
        try {
            ar = nhb.getNhapHang();
            NhapHangDTO nhd = new NhapHangDTO();
            for(int i=0; i<ar.size(); i++)
            {
                Vector row = new Vector();
                nhd = ar.get(i);
                row.add(nhd.getMaPNH());
                row.add(nhd.getMaNCC());
                row.add(nhd.getMaNV());
                row.add(nhd.getNgayLap());
                row.add(nhd.getTongTien());
                table.addRow(row);
            }
            ds = table;
            TableNhapHang.setModel(table);
        }
        catch (Exception e){  
        }
        Vector header2 = new Vector();
        header2.add("Mã nhà cung cấp");
        header2.add("Tên nhà cung cấp");
        header2.add("Địa chỉ");
        header2.add("Email");
        header2.add("Số điện thoại");
        DefaultTableModel table2 = new DefaultTableModel(header2, 0);
        ArrayList<NhaCungCapDTO> ar2 = null;
        try {
            ar2 = nccb.getNhaCungCap();
            NhaCungCapDTO nccd = new NhaCungCapDTO();
            for(int i=0; i< ar2.size(); i++)
            {
                Vector row = new Vector();
                nccd = ar2.get(i);
                row.add(nccd.getMaNCC());
                row.add(nccd.getTenNCC());
                row.add(nccd.getDiaChi());
                row.add(nccd.getEmail());
                row.add(nccd.getSdt());
                table2.addRow(row);
            }
            ds2 = table2;
            TableNhaCungCap.setModel(table2);
        }catch (Exception e) {
        }
        Vector header3 = new Vector();
        header3.add("Mã nhân viên");
        header3.add("Tên nhân viên");
        header3.add("Ngày sinh");
        DefaultTableModel table3 = new DefaultTableModel(header3, 0);
        ArrayList<NhanVienDTO> ar3 = null;
        try {
            ar3 = nvb.getNhanVien();
            NhanVienDTO nvd = new NhanVienDTO();
            for(int i=0; i< ar3.size(); i++)
            {
                Vector row = new Vector();
                nvd = ar3.get(i);
                row.add(nvd.getMaNV());
                row.add(nvd.getTenNV());
                row.add(nvd.getNgaySinh());
                table3.addRow(row);
            }
            ds3 = table3;
            TableNhanVien.setModel(table3);
        }catch (Exception e) {
        }
        Vector header4 = new Vector();
        header4.add("Mã sản phẩm");
        header4.add("Tên sản phẩm");
        header4.add("Đơn giá");
        header4.add("Số lượng");
        DefaultTableModel table4 = new DefaultTableModel(header4, 0);
        ArrayList<SanPhamDTO> ar4 = null;
        try {
            ar4 = spb.getSanPham();
            SanPhamDTO spd = new SanPhamDTO();
            for(int i=0; i< ar4.size(); i++)
            {
                Vector row = new Vector();
                spd = ar4.get(i);
                row.add(spd.getMaSP());
                row.add(spd.getTenSP());
                row.add(spd.getDonGia());
                row.add(spd.getSoLuongCo());
                table4.addRow(row);
            }
            ds4 = table4;
            TableSanPham.setModel(table4);
        }catch (Exception e) {
        }
        Vector header5 = new Vector();
        header5.add("Mã PNH");
        header5.add("Mã SP");
        header5.add("Số lượng");
        header5.add("Đơn giá");
        header5.add("Thành tiền");
        DefaultTableModel table5 = new DefaultTableModel(header5, 0);
        ArrayList<CtNhapHangDTO> ar5 = null;
        try {
            ar5 = ctnhb.getCtNhapHang();
            CtNhapHangDTO ctnhd = new CtNhapHangDTO();
            for(int i=0; i< ar5.size(); i++)
            {
                Vector row = new Vector();
                ctnhd = ar5.get(i);
                row.add(ctnhd.getMaPNH());
                row.add(ctnhd.getMaSanPham());
                row.add(ctnhd.getSoLuong());
                row.add(ctnhd.getDonGia());
                row.add(ctnhd.getThanhTien());
                table5.addRow(row);
            }
            ds5 = table5;
            TableChiTietNhapHang.setModel(table5);
        }catch (Exception e) {
        }
    }//GEN-LAST:event_btnHienThiMouseClicked

    private void TableNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNhapHangMouseClicked
        try{
        int n = TableNhapHang.getSelectedRow();
        cr = n;
        txtMaPhieuNhapHang.setText(TableNhapHang.getValueAt(n, 0).toString());
        txtMaNhaCungCap.setText(TableNhapHang.getValueAt(n, 1).toString());
        txtMaNhanVien.setText(TableNhapHang.getValueAt(n, 2).toString());
        txtNgayLap.setText(TableNhapHang.getValueAt(n, 3).toString());
        
        ArrayList<CtNhapHangDTO> ar5 = ctnhb.getCtNhapHang();
        Vector header5 = new Vector();
        header5.add("Mã PNH");
        header5.add("Mã SP");
        header5.add("Số lượng");
        header5.add("Đơn giá");
        header5.add("Thành tiền");
        DefaultTableModel table5 = new DefaultTableModel(header5, 0);
        try {
            ar5 = ctnhb.getCtNhapHang("MaPNH = " + "'" + txtMaPhieuNhapHang.getText() + "'");
            CtNhapHangDTO ctnhd = new CtNhapHangDTO();
            for(int i=0; i< ar5.size(); i++)
            {
                Vector row = new Vector();
                ctnhd = ar5.get(i);
                row.add(ctnhd.getMaPNH());
                row.add(ctnhd.getMaSanPham());
                row.add(ctnhd.getSoLuong());
                row.add(ctnhd.getDonGia());
                row.add(ctnhd.getThanhTien());
                table5.addRow(row);
            }
            ds5 = table5;
            TableChiTietNhapHang.setModel(table5);
        }catch (Exception e) {
        }
        }catch (Exception ex) {
            Logger.getLogger(NhaCungCapGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TableNhapHangMouseClicked

    private void TableNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNhaCungCapMouseClicked
        int n = TableNhaCungCap.getSelectedRow();
        cr2 = n;
        txtMaNhaCungCap.setText(TableNhaCungCap.getValueAt(n, 0).toString());
    }//GEN-LAST:event_TableNhaCungCapMouseClicked

    private void TableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNhanVienMouseClicked
        int n = TableNhanVien.getSelectedRow();
        cr3 = n;
        txtMaNhanVien.setText(TableNhanVien.getValueAt(n, 0).toString());
    }//GEN-LAST:event_TableNhanVienMouseClicked

    private void TableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSanPhamMouseClicked
        int n = TableSanPham.getSelectedRow();
        cr4 = n;
        txtMaSanPham.setText(TableSanPham.getValueAt(n, 0).toString());
        txtDonGia.setText(TableSanPham.getValueAt(n, 2).toString());
    }//GEN-LAST:event_TableSanPhamMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        try {
            NhapHangDTO nhd = new NhapHangDTO();
            nhd.setMaPNH(txtMaPhieuNhapHang.getText());
            nhd.setMaNCC(txtMaNhaCungCap.getText());
            nhd.setMaNV(txtMaNhanVien.getText());
            nhd.setNgayLap(txtNgayLap.getText());
            nhd.setTongTien(0);
            nhb.Insert(nhd);
            Vector row = new Vector();
            row.add(txtMaPhieuNhapHang.getText());
            row.add(txtMaNhaCungCap.getText());
            row.add(txtMaNhanVien.getText());
            row.add(txtNgayLap.getText());
            row.add(nhd.getTongTien());
            ds.addRow(row);
            TableNhapHang.setModel(ds);
        }
        catch (Exception e){
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnThemChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemChiTietMouseClicked
        try {
        CtNhapHangDTO ctnhd = new CtNhapHangDTO();
        ctnhd.setMaPNH(txtMaPhieuNhapHang.getText());
        ctnhd.setMaSanPham(txtMaSanPham.getText());
        ctnhd.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        ctnhd.setDonGia(Integer.parseInt(txtDonGia.getText()));
        ctnhd.setThanhTien(Integer.parseInt(txtDonGia.getText())*Integer.parseInt(txtSoLuong.getText()));
        ctnhb.Insert(ctnhd);
        Vector row = new Vector();
        row.add(txtMaPhieuNhapHang.getText());
        row.add(txtMaSanPham.getText());
        row.add(Integer.parseInt(txtSoLuong.getText()));
        row.add(Integer.parseInt(txtDonGia.getText()));
        row.add(Integer.parseInt(txtDonGia.getText())*Integer.parseInt(txtSoLuong.getText()));
        ds5.addRow(row);
        TableChiTietNhapHang.setModel(ds5);
        
        CtNhaCungCapDTO ctnccd = new CtNhaCungCapDTO();
        ctnccd.setMaNCC(txtMaNhaCungCap.getText());
        ctnccd.setMaSanPham(txtMaSanPham.getText());
        ctnccb.Insert(ctnccd);
        
        int tong=0;
        ArrayList<CtNhapHangDTO> arctnhd = null;
        try {
            arctnhd = ctnhb.getCtNhapHang();
            for(int i=0; i<arctnhd.size(); i++)
            {
                ctnhd = arctnhd.get(i);
                if(ctnhd.getMaPNH().equals(txtMaPhieuNhapHang.getText()))
                    tong = tong + ctnhd.getThanhTien();
            }
        } catch (Exception e) {
        }
        NhapHangDTO nhd = new NhapHangDTO();
        nhd.setMaPNH(txtMaPhieuNhapHang.getText());
        nhd.setMaNCC(txtMaNhaCungCap.getText());
        nhd.setMaNV(txtMaNhanVien.getText());
        nhd.setNgayLap(txtNgayLap.getText());
        nhd.setTongTien(tong);
        nhb.Update(nhd);
        ds.setValueAt(txtMaPhieuNhapHang.getText(), cr, 0);
        ds.setValueAt(txtMaNhaCungCap.getText(), cr, 1);
        ds.setValueAt(txtMaNhanVien.getText(), cr, 2);
        ds.setValueAt(txtNgayLap.getText(), cr, 3);
        ds.setValueAt(tong, cr, 4);
        TableNhapHang.setModel(ds);
        }
        catch (Exception e){
        }
        
        int soluong=Integer.parseInt(txtSoLuong.getText());
        SanPhamDTO spd = new SanPhamDTO();
        ArrayList<SanPhamDTO> arspd = null;
        try {
            arspd = spb.getSanPham();
            for(int i=0; i<arspd.size();i++)
            {
                spd = arspd.get(i);
                if(spd.getMaSP().equals(txtMaSanPham.getText()))
                {
                    int tam;
                    tam = spd.getSoLuongCo()+soluong;
                    spd.setSoLuongCo(spd.getSoLuongCo()+soluong);
                    spb.UpdateGia(spd);
                    ds4.setValueAt(tam, cr4, 3);
                    TableSanPham.setModel(ds4);
                    break;
                }
            }
        } catch (Exception e) {
        }
        refresh();
    }//GEN-LAST:event_btnThemChiTietMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        try {
            NhapHangDTO nhd = new NhapHangDTO();
            nhd.setMaPNH(txtMaPhieuNhapHang.getText());
            nhd.setMaNCC(txtMaNhaCungCap.getText());
            nhd.setMaNV(txtMaNhanVien.getText());
            nhd.setNgayLap(txtNgayLap.getText());
            nhb.Update(nhd);
            ds.setValueAt(txtMaPhieuNhapHang.getText(), cr, 0);
            ds.setValueAt(txtMaNhaCungCap.getText(), cr, 1);
            ds.setValueAt(txtMaNhanVien.getText(), cr, 2);
            ds.setValueAt(txtNgayLap.getText(), cr, 3);
            TableNhapHang.setModel(ds);
        } catch (Exception e) {
        }
        refresh();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnSuaChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaChiTietMouseClicked
        try {
            int soluongtruoc = 0;
            String MaSPTruoc = "";
            MaSPTruoc = ds5.getValueAt(cr5, 1).toString();
            CtNhapHangDTO ctnhd = new CtNhapHangDTO();
            ArrayList<CtNhapHangDTO> arrayctnh = null;
            try {
                arrayctnh = ctnhb.getCtNhapHang();
                for(int i=0; i<arrayctnh.size(); i++)
                {
                    ctnhd = arrayctnh.get(i);
                    if(ctnhd.getMaPNH().equals(txtMaPhieuNhapHang.getText()) && ctnhd.getMaSanPham().equals(txtMaSanPham.getText()))
                    {
                        soluongtruoc = ctnhd.getSoLuong();
                        break;
                    }
                }
            } catch (Exception e) {
            }
            
            
            
            ctnhd.setMaPNH(txtMaPhieuNhapHang.getText());
            ctnhd.setMaSanPham(txtMaSanPham.getText());
            ctnhd.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
            ctnhd.setDonGia(Integer.parseInt(txtDonGia.getText()));
            ctnhd.setThanhTien(Integer.parseInt(txtDonGia.getText())*Integer.parseInt(txtSoLuong.getText()));        
            ctnhb.UpdateMaSP(ctnhd,MaSPTruoc);
            ds5.setValueAt(txtMaPhieuNhapHang.getText(), cr5, 0);
            ds5.setValueAt(txtMaSanPham.getText(), cr5, 1);
            ds5.setValueAt(txtSoLuong.getText(), cr5, 2);
            TableChiTietNhapHang.setModel(ds5);
            
            int tong=0;
            ArrayList<CtNhapHangDTO> arctnhd = null;
            try {
                arctnhd = ctnhb.getCtNhapHang();
                for(int i=0; i<arctnhd.size(); i++)
                {
                    ctnhd = arctnhd.get(i);
                    if(ctnhd.getMaPNH().equals(txtMaPhieuNhapHang.getText()))
                        tong = tong + ctnhd.getThanhTien();
                }
            } catch (Exception e) {
            }
            NhapHangDTO nhd = new NhapHangDTO();
            nhd.setMaPNH(txtMaPhieuNhapHang.getText());
            nhd.setMaNCC(txtMaNhaCungCap.getText());
            nhd.setMaNV(txtMaNhanVien.getText());
            nhd.setNgayLap(txtNgayLap.getText());
            nhd.setTongTien(tong);
            nhb.Update(nhd);
            ds.setValueAt(txtMaPhieuNhapHang.getText(), cr, 0);
            ds.setValueAt(txtMaNhaCungCap.getText(), cr, 1);
            ds.setValueAt(txtMaNhanVien.getText(), cr, 2);
            ds.setValueAt(txtNgayLap.getText(), cr, 3);
            ds.setValueAt(tong, cr, 4);
            TableNhapHang.setModel(ds);
            
            //soluongtruoc ở hàng đầu
            int soluongsau=Integer.parseInt(txtSoLuong.getText());
            int soluong;
            soluong = soluongsau - soluongtruoc;
            SanPhamDTO spd = new SanPhamDTO();
            ArrayList<SanPhamDTO> arspd = null;
            try {
                arspd = spb.getSanPham();
                for(int i=0; i<arspd.size();i++)
                {
                    spd = arspd.get(i);
                    if(spd.getMaSP().equals(txtMaSanPham.getText()))
                    {
                        int tam;
                        tam = spd.getSoLuongCo()+soluong;
                        spd.setSoLuongCo(spd.getSoLuongCo()+soluong);
                        spb.UpdateGia(spd);
                        ds4.setValueAt(tam, cr4, 3);
                        TableSanPham.setModel(ds4);
                        break;
                    }
                }
            } catch (Exception e) {
            }
        }
        catch (Exception e){
        }
        refresh();
    }//GEN-LAST:event_btnSuaChiTietMouseClicked

    private void TableChiTietNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableChiTietNhapHangMouseClicked
        int n = TableChiTietNhapHang.getSelectedRow();
        cr5 = n;
        txtMaSanPham.setText(TableChiTietNhapHang.getValueAt(n, 1).toString());
        txtSoLuong.setText(TableChiTietNhapHang.getValueAt(n, 2).toString());
        txtDonGia.setText(TableChiTietNhapHang.getValueAt(n, 3).toString());
    }//GEN-LAST:event_TableChiTietNhapHangMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        try {
            NhapHangDTO nhd = new NhapHangDTO();
            nhd.setMaPNH(txtMaPhieuNhapHang.getText());
            nhd.setMaNCC(txtMaNhaCungCap.getText());
            nhd.setMaNV(txtMaNhanVien.getText());
            nhd.setNgayLap(txtNgayLap.getText());
            nhb.Delete(nhd);
            ds.removeRow(cr);
            TableNhapHang.setModel(ds);
        } catch (Exception e) {
        }
        refresh();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnXoaChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaChiTietMouseClicked
        try {
            CtNhapHangDTO ctnhd = new CtNhapHangDTO();
            ctnhd.setMaPNH(txtMaPhieuNhapHang.getText());
            ctnhd.setMaSanPham(txtMaSanPham.getText());
            ctnhd.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
            ctnhd.setDonGia(Integer.parseInt(txtDonGia.getText()));
            ctnhd.setThanhTien(Integer.parseInt(txtSoLuong.getText())*Integer.parseInt(txtDonGia.getText()));
            ctnhb.Delete(ctnhd);
            ds5.removeRow(cr5);
            TableChiTietNhapHang.setModel(ds5);
        } catch (Exception e) {
        }
        try {
            CtNhapHangDTO ctnhd = new CtNhapHangDTO();
            int tong=0;
            ArrayList<CtNhapHangDTO> arctnhd = null;
            try {
                arctnhd = ctnhb.getCtNhapHang();
                for(int i=0; i<arctnhd.size(); i++)
                {
                    ctnhd = arctnhd.get(i);
                    if(ctnhd.getMaPNH().equals(txtMaPhieuNhapHang.getText()))
                        tong = tong + ctnhd.getThanhTien();
                }
            } catch (Exception e) {
            }
            NhapHangDTO nhd = new NhapHangDTO();
            nhd.setMaPNH(txtMaPhieuNhapHang.getText());
            nhd.setMaNCC(txtMaNhaCungCap.getText());
            nhd.setMaNV(txtMaNhanVien.getText());
            nhd.setNgayLap(txtNgayLap.getText());
            nhd.setTongTien(tong);
            nhb.Update(nhd);
            ds.setValueAt(txtMaPhieuNhapHang.getText(), cr, 0);
            ds.setValueAt(txtMaNhaCungCap.getText(), cr, 1);
            ds.setValueAt(txtMaNhanVien.getText(), cr, 2);
            ds.setValueAt(txtNgayLap.getText(), cr, 3);
            ds.setValueAt(tong, cr, 4);
            TableNhapHang.setModel(ds);
        } catch (Exception e) {
        }
        refresh();
    }//GEN-LAST:event_btnXoaChiTietMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    public void refresh()
    {
        Vector header = new Vector();
        header.add("Mã phiếu nhập hàng");
        header.add("Mã nhà cung cấp");
        header.add("Mã nhân viên");
        header.add("Ngày lập");
        header.add("Tổng tiền");
        DefaultTableModel table = new DefaultTableModel(header,0);
        ArrayList<NhapHangDTO> ar = null;
        try {
            ar = nhb.getNhapHang();
            NhapHangDTO nhd = new NhapHangDTO();
            for(int i=0; i<ar.size(); i++)
            {
                Vector row = new Vector();
                nhd = ar.get(i);
                row.add(nhd.getMaPNH());
                row.add(nhd.getMaNCC());
                row.add(nhd.getMaNV());
                row.add(nhd.getNgayLap());
                row.add(nhd.getTongTien());
                table.addRow(row);
            }
            ds = table;
            TableNhapHang.setModel(table);
        }
        catch (Exception e){  
        }
        Vector header2 = new Vector();
        header2.add("Mã nhà cung cấp");
        header2.add("Tên nhà cung cấp");
        header2.add("Địa chỉ");
        header2.add("Email");
        header2.add("Số điện thoại");
        DefaultTableModel table2 = new DefaultTableModel(header2, 0);
        ArrayList<NhaCungCapDTO> ar2 = null;
        try {
            ar2 = nccb.getNhaCungCap();
            NhaCungCapDTO nccd = new NhaCungCapDTO();
            for(int i=0; i< ar2.size(); i++)
            {
                Vector row = new Vector();
                nccd = ar2.get(i);
                row.add(nccd.getMaNCC());
                row.add(nccd.getTenNCC());
                row.add(nccd.getDiaChi());
                row.add(nccd.getEmail());
                row.add(nccd.getSdt());
                table2.addRow(row);
            }
            ds2 = table2;
            TableNhaCungCap.setModel(table2);
        }catch (Exception e) {
        }
        Vector header3 = new Vector();
        header3.add("Mã nhân viên");
        header3.add("Tên nhân viên");
        header3.add("Ngày sinh");
        DefaultTableModel table3 = new DefaultTableModel(header3, 0);
        ArrayList<NhanVienDTO> ar3 = null;
        try {
            ar3 = nvb.getNhanVien();
            NhanVienDTO nvd = new NhanVienDTO();
            for(int i=0; i< ar3.size(); i++)
            {
                Vector row = new Vector();
                nvd = ar3.get(i);
                row.add(nvd.getMaNV());
                row.add(nvd.getTenNV());
                row.add(nvd.getNgaySinh());
                table3.addRow(row);
            }
            ds3 = table3;
            TableNhanVien.setModel(table3);
        }catch (Exception e) {
        }
        Vector header4 = new Vector();
        header4.add("Mã sản phẩm");
        header4.add("Tên sản phẩm");
        header4.add("Đơn giá");
        header4.add("Số lượng");
        DefaultTableModel table4 = new DefaultTableModel(header4, 0);
        ArrayList<SanPhamDTO> ar4 = null;
        try {
            ar4 = spb.getSanPham();
            SanPhamDTO spd = new SanPhamDTO();
            for(int i=0; i< ar4.size(); i++)
            {
                Vector row = new Vector();
                spd = ar4.get(i);
                row.add(spd.getMaSP());
                row.add(spd.getTenSP());
                row.add(spd.getDonGia());
                row.add(spd.getSoLuongCo());
                table4.addRow(row);
            }
            ds4 = table4;
            TableSanPham.setModel(table4);
        }catch (Exception e) {
        }
        Vector header5 = new Vector();
        header5.add("Mã PNH");
        header5.add("Mã SP");
        header5.add("Số lượng");
        header5.add("Đơn giá");
        header5.add("Thành tiền");
        DefaultTableModel table5 = new DefaultTableModel(header5, 0);
        ArrayList<CtNhapHangDTO> ar5 = null;
        try {
            ar5 = ctnhb.getCtNhapHang();
            CtNhapHangDTO ctnhd = new CtNhapHangDTO();
            for(int i=0; i< ar5.size(); i++)
            {
                Vector row = new Vector();
                ctnhd = ar5.get(i);
                row.add(ctnhd.getMaPNH());
                row.add(ctnhd.getMaSanPham());
                row.add(ctnhd.getSoLuong());
                row.add(ctnhd.getDonGia());
                row.add(ctnhd.getThanhTien());
                table5.addRow(row);
            }
            ds5 = table5;
            TableChiTietNhapHang.setModel(table5);
        }catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapHangGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelChiTiet;
    private javax.swing.JLabel LabelDonGia;
    private javax.swing.JLabel LabelMaNhaCungCap;
    private javax.swing.JLabel LabelMaNhanVien;
    private javax.swing.JLabel LabelMaPhieuNhapHang;
    private javax.swing.JLabel LabelMaSanPham;
    private javax.swing.JLabel LabelNgayLap;
    private javax.swing.JLabel LabelPhieuNhapHang;
    private javax.swing.JLabel LabelSoLuong;
    private javax.swing.JTable TableChiTietNhapHang;
    private javax.swing.JTable TableNhaCungCap;
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JTable TableNhapHang;
    private javax.swing.JTable TableSanPham;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaChiTiet;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemChiTiet;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaNhaCungCap;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMaPhieuNhapHang;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
